### ISSUE TITLE
Deprecate packageVersion in favor of version

### ISSUE THREAD

**Issue by aiyengar2** [rancher/charts-build-scripts#40]
Instead of having a packageVersion appended to the version presumed from the chart, we will deprecate the packageVersion flag entirely. Instead, the version will be specified in the package.yaml itself.

---

This will involve removing all references of it from the code, including but not limited to:

https://github.com/rancher/charts-build-scripts/blob/cae97e473d936f6b4dd11504f4b5ced7df989d24/pkg/charts/chart.go#L84

https://github.com/rancher/charts-build-scripts/blob/cae97e473d936f6b4dd11504f4b5ced7df989d24/pkg/charts/additionalchart.go#L188

https://github.com/rancher/charts-build-scripts/blob/cae97e473d936f6b4dd11504f4b5ced7df989d24/pkg/helm/export.go#L30

https://github.com/rancher/charts-build-scripts/blob/cae97e473d936f6b4dd11504f4b5ced7df989d24/pkg/charts/parse.go#L99

https://github.com/rancher/charts-build-scripts/blob/cae97e473d936f6b4dd11504f4b5ced7df989d24/pkg/options/package.go#L17

---

### If we want to introduce the version on `make charts`

e.g. the version will that we patch to will be ignored, even if it is patched like in

https://github.com/rancher/charts/blob/d688738828eba441a4af9621e5bbed449aa744a8/packages/rancher-monitoring/generated-changes/patch/Chart.yaml.patch#L55-L56

We just need to modify https://github.com/rancher/charts-build-scripts/blob/cae97e473d936f6b4dd11504f4b5ced7df989d24/pkg/charts/additionalchart.go#L192 to take in chartVersion instead of packageVersion and drop all of the following logic

https://github.com/rancher/charts-build-scripts/blob/cae97e473d936f6b4dd11504f4b5ced7df989d24/pkg/helm/export.go#L40-L53

**Comment by aiyengar2** [comment]
I would recommend option 2, introducing the version in `make charts`, since it is far easier of a change.

Once this change is made, we should cut a v0.3.0 release of charts-build-scripts, since it is a breaking change that is deprecating a field.

**Comment by cbron** [comment]
Isn't 0.2.0 new in 2.6 already ? Is there reason we can't reuse that one

**Comment by aiyengar2** [comment]
> Isn't 0.2.0 new in 2.6 already ? Is there reason we can't reuse that one

We could. But the versioning of the charts-build-scripts is technically independent of the Rancher release, so we should bump it.

I don’t think anyone is using the scripts outside of Rancher though, so if we want to avoid cutting a new release I think that should be fine.

**Comment by cbron** [comment]
Well we can do 0.2.1, I just don't think we need to go to 0.3 and do the whole "breaking changes" api move if we never use them.

**Comment by jiaqiluo** [comment]
We decided to keep the `packageVesion` and also introduce a new option: `version`. 
See the new issue for more info: ttps://github.com/rancher/charts-build-scripts/issues/40
