### ISSUE TITLE
Regenerate index.yaml to only contain validating charts + local charts

### ISSUE THREAD

**Issue by aiyengar2** [rancher/charts-build-scripts#54]
Currently, it is always a manual step to delete the old index.yaml, assets, and charts related to an unreleased chart that will no longer be released.

Instead, `make charts` should generate an index.yaml based on a **new, sorted index.yaml that merges**:
- All index.yamls from charts we validate against
- The current charts tracked in packages/

Once the index is generated, we should clean up any charts/ or assets/ whose URLs are untracked in the merged index.yaml.

Epic Issue: https://github.com/rancher/charts-build-scripts/issues/60

**Comment by Jono-SUSE-Rancher** [comment]
Hey @aiyengar2, can we do manual steps in the release process for v2.6.0 if we bump this to v2.6.1?

**Comment by aiyengar2** [comment]
> Hey @aiyengar2, can we do manual steps in the release process for v2.6.0 if we bump this to v2.6.1?

Yes that sounds good!

**Comment by cbron** [comment]
Can we move this to 2.6.2 ?
