### ISSUE TITLE
EPIC: charts-build-scripts v0.3.0 changes

### ISSUE THREAD

**Issue by cbron** [rancher/charts-build-scripts#60]
This issue is an EPIC to track several changes in charts-build-scripts + rancher/charts that need to be addressed.

1. https://github.com/rancher/charts-build-scripts/issues/62
2. https://github.com/rancher/charts-build-scripts/issues/61
3. https://github.com/rancher/charts-build-scripts/issues/54
4. https://github.com/rancher/charts-build-scripts/issues/63

**Comment by aiyengar2** [comment]
Discussed this issue offline, the scope of this issue is to address multiple, independent concerns. Therefore, I'm treating this issue as an Epic to track the changes necessary to address release process issues for 2.6.2.

Updating issue description accordingly with newly clarified scope.

**Comment by aiyengar2** [comment]
Migration docs: https://github.com/rancher/charts-build-scripts/wiki/Migrating-to-charts-build-scripts-v0.3.0

cc: @jiaqiluo @cbron if you want to "review"

**Comment by cbron** [comment]
Pushing as we decided to do all this for 2.6.4

**Comment by aiyengar2** [comment]
Migration is done for dev-v2.6! will open up a followup epic for 2.5 migration steps.
