### ISSUE TITLE
Usage example for new charts

### ISSUE THREAD

**Issue by oxr463** [rancher/charts-build-scripts#82]
How would I use this for new charts? What does it do?

**Comment by PennyScissors** [comment]
@oxr463 The chart build scripts are used internally as part of the Make workflow in rancher/charts and they are not meant to be used standalone. Please refer to the documentation [here](https://github.com/rancher/charts/#rancher-charts).

**Comment by aiyengar2** [comment]
@oxr463 are you trying to develop a new charts repository that uses

**Comment by oxr463** [comment]
I was hoping to see if I could use this for our EIO charts: https://github.com/rancher/eio-charts/tree/dev

**Comment by prachidamle** [comment]
This is a question that is answered and can be closed, assigining to Mapps backlog in case there is a followup question.
