### ISSUE TITLE
Upgrading the charts build script to latest version v0.4.4 in rancher/charts breaks validation step.

### ISSUE THREAD

**Issue by rohitsakala** [rancher/charts-build-scripts#96]
1. Understand what the CI validation step does ie. `make validate. 
2. Document the `make validate`. 
3. Find out why upgrading charts build script fails and fix it.
4. Update the Github action of Generate Regsync config file - Remove the export version command.

**Comment by lucasmlp** [comment]
Error on version v0.4.4
![image.png](https://zube.io/files/rancher/fd45034599c4a81bfc865dda307220e1-image.png)
